
const columns=[
    {key: "id", width:250, title: "ID"},
    {key: "championName", width:250, title: "Champion"},
    {key: "assists", width:250, title: "Assists"},
    {key: "baronKills", width:250, title: "Baron_Kills"},
    {key: "bountyLevel", width:250, title: "Bounty_Level"},
    {key: "champExperience", width:250, title: "Champion_EXP"},
    {key: "champLevel", width:250, title: "Champion_Level"},
    {key: "damageDealtToObjectives", width:250, title:"Objective_Damage"},
    {key: "damageSelfMitigated", width:250, title:"Damage_selfMitigated"},
    {key: "deaths", width:250, title:"Deaths"},
    {key: "dragonKills", width:250, title:"Dragon_Kills"},
    {key: "firstBloodAssist", width:250, title:"FirstBlood_Assists"},
    {key: "firstBllodKill", width:250, title:"First_Blood"},
    {key: "gameEndedInSurrender", width:250, title:"Surrender"},
    {key: "goldEarned", width:250, title: "Gold_Earned"},
    {key: "goldSpent", width:250, title: "Gold_Spent"},
    {key: "individualPosition", width:250, title: "Lane"},
    {key: "inhibitoKills", width:250, title: "Enemy_Inhibitor_Destroyed"},
    {key: "inhibitorsLost", width:250, title: "Teams_Inhibitor_Destoryed"},
    {key: "item0", width:250, title: "Item_0"},
    {key: "item1", width:250, title: "Item_1"},
    {key: "item2", width:250, title: "Item_2"},
    {key: "item3", width:250, title: "Item_3"},
    {key: "item4", width:250, title: "Item_4"},
    {key: "item5", width:250, title: "Item_5"},
    {key: "item6", width:250, title: "Item_6"},
    {key: "largestCriticalStrike", width:250, title: "Largest_Crit_Strike"},
    {key: "largetKillingSpree", width:250, title: "Longest_Killing_Spree"},
    {key: "longestTimeSpentLiving", width:250, title:"Longest_Time_Alive"},
    {key: "magicDamageDealtToChampions", width:250, title:"Magic_Damage"},
    {key: "objectivesStolen", width:250, title: "Objective_Stolen"},
    {key: "physicalDamageDealtToChampions", width:250, title: "Physical_Damage_Towards_Champions"},
    {key: "physicalDamageTaken", width:250, title: "Physical_Damage_Taken"},
    {key: "spell1Casts", width:250, title: "Q_Casted"},
    {key: "spell2Casts", width:250, title: "W_Casted"},
    {key: "spell3Casts", width:250, title: "E_Casted"},
    {key: "spell4Casts", width:250, title: "R_Casted"},
    {key: "summoner1Casts", width:250, title: "D_Casted"},
    {key: "summoner2Casts", width:250, title: "F_Casted"},
    {key: "teamEarlySurrendered", width:250, title: "Team_Surrender"},
    {key: "timeCCingOther", width:250, title: "Time_CC_Others"},
    {key: "timePlayed", width:250, title: "Game_Total_Time"},
    {key: "totalDamageDealtToChampions", width:250, title: "Total_Damage_To_Champs"},
    {key: "totalDamageShieldedOnTeammates", width:250, title: "Shelded_Damage_On_Teammates"},
    {key: "totalHeal", width:250, title: "Total_Heal"},
    {key: "totalHealsOnTeammates", width:250, title: "Total_Heal_On_Teammates"},
    {key: "totalMinionsKilled", width:250, title: "Total_Minion_Killed"},
    {key: "totalTimeCCDealt", width:250, title: "Total_CC_Dealt"},
    {key: "totalTimeSpentDead", width:250, title: "Total_Time_Dead"},
    {key: "trueDamageDealtToChampions", width:250, title: "True_Damage_Towards_Champs"},
    {key: "trueDamageTaken", width:250, title: "True_Damage_Taken"},
    {key: "turretTakedowns", width:250, title: "Turret_Takedowns"},
    {key: "turretLost", width:250, title: "Turrets_Lost"},
    {key: "visionScore", width:250, title: "Vision_Score"},
    {key: "visionWardsBoughtInGame", width:250, title: "Vision_Ward_Bought"},
    {key: "wardsKilled", width:250, title: "Wards_Destroyed"},
    {key: "wardsPlaces", width:250, title: "Ward_Placed"},
    {key: "win", width:250, title: "win"}
];

export {columns}