
const columns=[
    {key: "id", width:250, title: "ID"},
    {key: "championName", width:250, title: "Champion"},
    {key: "assists", width:250, title: "Assists"},
    {key: "baronKills", width:250, title: "Baron_Kills"},
    {key: "bountyLevel", width:250, title: "Bounty_Level"},
    {key: "champExperience", width:250, title: "Champion_EXP"},
    {key: "champLevel", width:250, title: "Champion_Level"},
    {key: "damageDealtToObjectives", width:250, title:"Objective_Damage"},
    {key: "damageSelfMitigated", width:250, title:"Damage_selfMitigated"},
    {key: "deaths", width:250, title:"Deaths"},
    {key: "dragonKills", width:250, title:"Dragon_Kills"},
    {key: "firstBloodAssist", width:250, title:"FirstBlood_Assists"},
    {key: "firstBloodKill", width:250, title:"First_Blood"},
    {key: "gameEndedInSurrender", width:250, title:"Surrender"},
    {key: "goldEarned", width:250, title: "Gold_Earned"},
    {key: "goldSpent", width:250, title: "Gold_Spent"},
    {key: "individualPosition", width:250, title: "Lane"},
    {key: "inhibitorKills", width:250, title: "Enemy_Inhibitor_Destroyed"},
    {key: "inhibitorsLost", width:250, title: "Teams_Inhibitor_Destoryed"},
    {key: "item0", width:250, title: "Item_0"},
    {key: "item1", width:250, title: "Item_1"},
    {key: "item2", width:250, title: "Item_2"},
    {key: "item3", width:250, title: "Item_3"},
    {key: "item4", width:250, title: "Item_4"},
    {key: "item5", width:250, title: "Item_5"},
    {key: "item6", width:250, title: "Item_6"},
    {key: "kills", width:250, title: "Kills"},
    {key: "largestCriticalStrike", width:250, title: "Largest_Crit_Strike"},
    {key: "largestKillingSpree", width:250, title: "Largest_Killing_Spree"},
    {key: "longestTimeSpentLiving", width:250, title:"Longest_Time_Alive"},
    {key: "magicDamageDealtToChampions", width:250, title:"Magic_Damage"},
    {key: "objectivesStolen", width:250, title: "Objective_Stolen"},
    {key: "physicalDamageDealtToChampions", width:250, title: "Physical_Damage_Towards_Champions"},
    {key: "physicalDamageTaken", width:250, title: "Physical_Damage_Taken"},
    {key: "spell1Casts", width:250, title: "Q_Casted"},
    {key: "spell2Casts", width:250, title: "W_Casted"},
    {key: "spell3Casts", width:250, title: "E_Casted"},
    {key: "spell4Casts", width:250, title: "R_Casted"},
    {key: "summoner1Casts", width:250, title: "D_Casted"},
    {key: "summoner2Casts", width:250, title: "F_Casted"},
    {key: "teamEarlySurrendered", width:250, title: "Team_Surrender"},
    {key: "timeCCingOthers", width:250, title: "Time_CC_Others"},
    {key: "timePlayed", width:250, title: "Game_Total_Time"},
    {key: "totalDamageDealtToChampions", width:250, title: "Total_Damage_To_Champs"},
    {key: "totalDamageShieldedOnTeammates", width:250, title: "Shelded_Damage_On_Teammates"},
    {key: "totalHeal", width:250, title: "Total_Heal"},
    {key: "totalHealsOnTeammates", width:250, title: "Total_Heal_On_Teammates"},
    {key: "totalMinionsKilled", width:250, title: "Total_Minion_Killed"},
    {key: "totalTimeCCDealt", width:250, title: "Total_CC_Dealt"},
    {key: "totalTimeSpentDead", width:250, title: "Total_Time_Dead"},
    {key: "trueDamageDealtToChampions", width:250, title: "True_Damage_Towards_Champs"},
    {key: "trueDamageTaken", width:250, title: "True_Damage_Taken"},
    {key: "turretTakedowns", width:250, title: "Turret_Takedowns"},
    {key: "turretsLost", width:250, title: "Turrets_Lost"},
    {key: "visionScore", width:250, title: "Vision_Score"},
    {key: "visionWardsBoughtInGame", width:250, title: "Vision_Ward_Bought"},
    {key: "wardsKilled", width:250, title: "Wards_Destroyed"},
    {key: "wardsPlaced", width:250, title: "Ward_Placed"},
    {key: "win", width:250, title: "win"}
];

const x_labels = ['Top', 'Middle', 'Jungle', 'Bottom', 'Support'];

const graphButtonOptions = [
    'assists', 'Baron_Kills', 'Champion_EXP', 'Champion_Level', 
    'Objective_Damage', 'Damage_selfMitigated','Deaths', 'Dragon_Kills', 'FirstBlood_Assits', 'First_Blood',
    'Surrendered', 'Gold_Earned', 'Gold_Spent', 'Lane', 'Enemy_Inhibitor_Destroyed',
    'Kills', 'Crit_Strike', 'Killing_Spree', 'Time_Alive', 'Magic_Damage', 'Objective_Stolen',
    'Physical_Damage', 'Physical_Damage_Taken', 'Q_Casted', 'W_Casted', 'E_Casted', 'R_Casted',
    'D_Casted', 'F_Casted', 'Time_CC_Others', 'Game_Total_Time', 'Total_Damage_To_champs',
    'Shelded_Damage_On_Teammates', 'Total_Heal', 'Total_Heal_Towards_Teammates', 'Total_Minions_Killed',
    'Total_Time_Dead', 'True_Damage_Towards_Champs', 'True_Damage_Taken', 'Turret_Takedowns',
    'Turrets_Lost', 'Vision_Score', 'Vision_Ward_Bought', 'Wards_Destroyed', 'Wards_Placed', 'Wins'];


export {columns, x_labels, graphButtonOptions}